server:
  port: 9005

#Configurations H2
spring:
  application:
    name: microservice-products
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  #défini l'encodage pour data.sql
  datasource:
    sql-script-encoding: UTF-8

#Nos configurations

my-configs:
  limitDeProduits: 3

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.126.226.2:9102/eureka/
