spring:
  application:
    name: zuul-server
  #Spring Security
  security:
    user:
      name: utilisateur
      password: mdp

server:
  port: 9004

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.126.226.2:9102/eureka/

