spring:
  application:
    name: microservice-orders
  #Configurations H2
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  #défini l'encodage pour data.sql
  datasource:
    sql-script-encoding: UTF-8

server:
  port: 9002

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
