spring:
  application:
    name: microservice-clientui

server:
  port: 80
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.126.226.2:9102/eureka/
