server:
  port: 9102

spring:
  application:
    name: eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.126.226.2:9102/eureka/
    registerWithEureka: false
    fetchRegistry: false
