spring:
  application:
    name: microservice-payment
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    sql-script-encoding: UTF-8

server:
  port: 9003


#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.126.226.2:9102/eureka/